FinalParameterPortal/Controllers/HomeController.cs
using FinalParameterPortal.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalParameterPortal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            List<string> availableServices = new List<string>();
            availableServices.Add("CRA");
            availableServices.Add("CRA_FI");
            availableServices.Add("FINAL");
            availableServices.Add("ICS");
            availableServices.Add("Credit_Hub");
            availableServices.Add("NCO");
            availableServices.Add("RKI");

            ServiceManager mgr = new ServiceManager();
            Dictionary<string, bool> servicesDictionary = new Dictionary<string, bool>();

            foreach (string sName in availableServices)
            {
                bool isRunning = mgr.IsServiceRunning(sName);
                servicesDictionary.Add(sName, isRunning);
            }

            return View(servicesDictionary);
        }
    }
}

FinalParameterPortal/Controllers/SettingsController.cs
using FinalParameterPortal.Helpers;
using FinalParameterPortal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;

namespace FinalParameterPortal.Controllers
{
    public class SettingsController : Controller
    {
        public ActionResult Overview()
        {
            SettingsModel settings = new SettingsModel();
            settings.Manager.GetAll();
            return View(settings);
        }

        public ActionResult Save(List<ServiceModel> _services)
        {
            if (_services != null && _services.Count() > 0)
            {
                try
                {
                    ServiceManager manager = new ServiceManager();
                    manager.Services = _services;
                    manager.Save();
                }
                catch (Exception e)
                {                    
                    TempData["ErrorMessages"] = e.Message;
                    return PartialView("_ServicesSettings", _services);
                }
            }

            //return PartialView("_ServicesSettings", _services);
            return RedirectToAction("Index", "Home");
        }
    }
}

FinalParameterPortal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

FinalParameterPortal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

FinalParameterPortal/Views/Home/Index.cshtml
@model Dictionary<string, bool>

@{
    ViewBag.Title = "NCO Admin - Services";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section featured {
    
    <section id="services-status" style="color: black;">
    <div class="container">
        <div class="box first">
			<h1 class="text-center" style="margin-bottom:50px;">Services Overview</h1>
            <div class="row">
                <div class="col-md-3 col-xs-12"></div>

				@if (Model != null && Model.Count() > 0)
				{
					foreach (KeyValuePair<string, bool> pair in Model)
					{
						string cssClass = string.Empty;
                        string imgSrc = string.Empty;
						string displayStatus = string.Empty;
						
						if (pair.Value == true)
						{							
                            cssClass = "textOnline";
                            imgSrc = "Images/online-icon.png";
							displayStatus = "Running";
						}
						else {
							cssClass = "textOffline";
                            imgSrc = "Images/offline-icon.png";
							displayStatus = "Stopped";
						}
                        
                        <div class="col-xs-1 col-xs-6">
                              <div class="center">
                                <img src="@imgSrc" alt="Avatar" class="image">
                                <div class="middle">
                                    <div class="@cssClass">@displayStatus</div>
                                </div>
                                <h4>@pair.Key</h4>
                              </div>
                            </div>
						
						//<div class="col-xs-1 col-xs-6">
						//	<div class="center">
						//		<i class="@cssClass">@displayStatus</i>
						//		<h4>@pair.Key</h4>
						//		@*<p></p>*@
						//	</div>
						//</div>
					}
				}
				else
				{
					<div class="col-xs-12">
						<div class="center">
							<i class="icon-thumbs-up icon-md icon-color6"></i>
							<h4>What services?</h4>
							<p>We didn't have any <code>SystemName</code>s through which to loop and show the status for.</p>
						</div>
					</div><!--/.col-md-4-->
				}
				
				
				
            </div>
			
			<div class="row" style="margin-top:50px;" id="actions">
				<div class="col-xs-12 text-center">
					@Html.ActionLink("Turn services on and off", "Overview", "Settings", null, new { @class = "btn btn-primary btn-lg" })
				</div>
			</div>

		</div>
    </div>
</section>
    <section>
        <footer id="footer">
            <img src="~/Images/footer.PNG" class="stretch" />
        </footer>
    </section>
}